export const todoConstantsAdd = {
    TODO_ADD_REQUEST: 'TODO_ADD_REQUEST',
    TODO_ADD_SUCCESS: 'TODO_ADD_SUCCESS',
    TODO_ADD_FAILURE: 'TODO_ADD_FAILURE'
};

export const todoConstantsDelete = {
    TODO_DELETE_REQUEST: 'TODO_DELETE_REQUEST',
    TODO_DELETE_SUCCESS: 'TODO_DELETE_SUCCESS',
    TODO_DELETE_FAILURE: 'TODO_DELETE_FAILURE'
};
